config/routes.rb
Rails.application.routes.draw do
  resources :lists do
    member do
      delete :delete
      patch :restore
    end
    resources :list_items
  end
  get 'trash' => "lists#trash", as: "trash"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/list.rb
class List < ApplicationRecord
  include SoftDeletable
  has_many :list_items, dependent: :destroy

  def is_deleted?
    deleted_at != nil
  end
end

app/models/list_item.rb
class ListItem < ApplicationRecord
  include SoftDeletable
  belongs_to :list
  has_many :tags
end

app/models/tag.rb
class Tag < ApplicationRecord
  belongs_to :list_item
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/list_items_controller.rb
class ListItemsController < ApplicationController
  before_action :set_list, only:[:index, :new, :create, :edit, :update, :destroy, :show]
  before_action :set_list_item, only: [:show, :edit, :update, :destroy]

  # GET /list_items
  # GET /list_items.json
  def index
    @list_items = @list.list_items
  end

  # GET /list_items/1
  # GET /list_items/1.json
  def show
  end

  # GET /list_items/new
  def new
    @list_item = ListItem.new
    render
  end

  # GET /list_items/1/edit
  def edit
    @tags = Tag.all
  end

  # POST /list_items
  # POST /list_items.json
  def create
    @tags = Tag.all
    @list_item = @list.list_items.new(list_item_params)

    respond_to do |format|
      if @list_item.save
        format.html { redirect_to list_path(@list), notice: 'List item was successfully created.' }
        format.json { render :show, status: :created, location: @list_item }
      else
        format.html { render :new }
        format.json { render json: @list_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /list_items/1
  # PATCH/PUT /list_items/1.json
  def update
    respond_to do |format|
      if @list_item.update(list_item_params)
        format.html { redirect_to list_path(@list), notice: 'List item was successfully updated.' }
        format.json { render :show, status: :ok, location: @list_item }
      else
        format.html { render :edit }
        format.json { render json: @list_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /list_items/1
  # DELETE /list_items/1.json
  def destroy
    @list_item.destroy
    respond_to do |format|
      format.html { redirect_to list_path(@list), notice: 'List item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def set_list
      @list = List.find params[:list_id]
      rescue ActiveRecord::RecordNotFound
        redirect_to(root_url, :notice => 'Record not found')
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_list_item
      @list_item = @list.list_items.find(params[:id])
      rescue ActiveRecord::RecordNotFound
        redirect_to(root_url, :notice => 'Record not found')
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def list_item_params
      params.require(:list_item).permit(:list_id, :name, :deleted_at, :deleted, :tag_id)
    end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:show, :edit, :update, :destroy, :delete, :restore]

  # GET /lists
  # GET /lists.json
  def index
    @lists = List.all
  end

  # GET /lists/1
  # GET /lists/1.json
  def show
    @list_items = @list.list_items
  end

  # GET /lists/new
  def new
    @list = List.new
  end

  # GET /lists/1/edit
  def edit
  end

  # POST /lists
  # POST /lists.json
  def create
    @list = List.new(list_params)

    respond_to do |format|
      if @list.save
        format.html { redirect_to @list, notice: 'List was successfully created.' }
        format.json { render :show, status: :created, location: @list }
      else
        format.html { render :new }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lists/1
  # PATCH/PUT /lists/1.json
  def update
    respond_to do |format|
      if @list.update(list_params)
        format.html { redirect_to @list, notice: 'List was successfully updated.' }
        format.json { render :show, status: :ok, location: @list }
      else
        format.html { render :edit }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lists/1
  # DELETE /lists/1.json
  def destroy
    @list.destroy(:soft)
    respond_to do |format|
      format.html { redirect_to lists_url, notice: 'List was successfully destroy.' }
      format.json { head :no_content }
    end
  end

  def delete
    @list.destroy(:hard)
    respond_to do |format|
      format.html { redirect_to lists_url, notice: 'List was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  def restore
    @list.update(deleted_at: nil)
    respond_to do |format|
      format.html { redirect_to lists_url, notice: 'List was successfully restored.' }
      format.json { head :no_content }
    end
  end

  def trash
    @soft_delete_lists = List.unscope(:where).where("deleted_at IS NOT NULL")
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_list
      @list = List.unscope(:where).find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def list_params
      params.require(:list).permit(:name, :deleted_at, :deleted)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/list_items_helper.rb
module ListItemsHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Task3</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/list_items/_form.html.erb
<% if @list_item.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@list_item.errors.count, "error") %> prohibited this list_item from being saved:</h2>

    <ul>
    <% @list_item.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<div class="field">
  <%= f.label :name %>
  <%= f.text_field :name, id: :list_item_name %>
</div>

<div class="">
  <%= f.label :tag_id %>
  <%= f.collection_select :tag_id, @tags, :id, :name, { prompt: "-- Choose tag" }, { class: 'form-control ' } %>
</div>

<div class="actions">
  <%= f.submit %>
</div>

app/views/list_items/edit.html.erb
<h1>Editing List Item</h1>

<%= form_for @list_item, url: list_list_item_path(@list), multipart: true, html: { class: "form-horizontal form-bordered", method: :patch } do |f| %>
  <%= render partial: 'form', locals: {f: f, post: @list_item} %>
<% end %>

app/views/list_items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>List Items</h1>

<table>
  <thead>
    <tr>
      <th>List</th>
      <th>Name</th>
      <th>Deleted at</th>
      <th>Deleted</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @list_items.each do |list_item| %>
      <tr>
        <td><%= list_item.list %></td>
        <td><%= list_item.name %></td>
        <td><%= list_item.deleted_at %></td>
        <td><%= list_item.deleted %></td>
        <td><%= link_to 'Show', list_item %></td>
        <td><%= link_to 'Edit', edit_list_item_path(list_item) %></td>
        <td><%= link_to 'Destroy', list_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New List Item', new_list_item_path %>

app/views/list_items/new.html.erb
<h1>New List Item</h1>

<%= form_for @list_item, url: list_list_items_path(@list), multipart: true, html: { class: "form-horizontal form-bordered", method: :post } do |f| %>
  <%= render partial: 'form', locals: {f: f, post: @list_item} %>
<% end %>

<%#= render 'form', list_item: @list_item %>

<%#= link_to 'Back', list_items_path %>

app/views/list_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>List Name:</strong>
  <%= @list_item.list.name %>
</p>

<p>
  <strong>Name:</strong>
  <%= @list_item.name %>
</p>

<p>
  <strong>Tag:</strong>
  <% @list_item.tags.each do |tag| %>
    <%= tag.name %>
  <% end %>
</p>

<%= link_to 'Back', list_path(@list) %>

app/views/lists/_form.html.erb
<%= form_with(model: list, local: true) do |form| %>
  <% if list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(list.errors.count, "error") %> prohibited this list from being saved:</h2>

      <ul>
      <% list.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :list_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/lists/edit.html.erb
<h1>Editing List</h1>

<%= render 'form', list: @list %>

<%= link_to 'Show', @list %> |
<%= link_to 'Back', lists_path %>

app/views/lists/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Lists</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @lists.each do |list| %>
      <tr>
        <td><%= list.name %></td>
        <td><%= link_to 'Show', list %></td>
        <td><%= link_to 'Edit', edit_list_path(list) %></td>
        <td><%= link_to 'Delete', list, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <td><%= link_to "Destroy", soft_delete_list_path(id: list), method: :patch %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New List', new_list_path %>

<h1>Soft Delete Lists</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Deleted at</th>
      <th>Deleted</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @soft_delete_lists.each do |list| %>
      <tr>
        <td><%= list.name %></td>
        <td><%= list.deleted_at %></td>
        <td><%= list.deleted %></td>
        <td><%= link_to 'Show', list %></td>
        <td><%= link_to 'Edit', edit_list_path(list) %></td>
        <td><%= link_to 'Delete', list, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/lists/new.html.erb
<h1>New List</h1>

<%= render 'form', list: @list %>

<%= link_to 'Back', lists_path %>

app/views/lists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @list.name %>
</p>

<% if @list.is_deleted? %>
<p>
  <strong>Deleted at:</strong>
  <%= @list.deleted_at %>
</p>

<p>
  <strong>Deleted:</strong>
  <%= @list.deleted %>
</p>
<% end %>

<h1>List Items</h1>

<% if @list_items.any? %>
  <table>
    <thead>
      <tr>
        <th>Name</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @list_items.each do |list| %>
        <tr>
          <td><%= list.name %></td>
          <td><%= link_to 'Show', list_list_item_path(list_id: @list, id: list) %></td>
          <td><%= link_to 'Edit', edit_list_list_item_path(list_id: @list, id: list) %></td>
          <td><%= link_to 'Delete', list_list_item_path(list_id: @list, id: list), method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  N/A
<% end %>

<br><br><br>

<% if !@list.is_deleted? %>
  <%= link_to "Add New Item", new_list_list_item_path(@list) %> |
<% end %>
<%= link_to 'Edit', edit_list_path(@list) %> |
<%= link_to 'Back', lists_path %>

app/views/lists/trash.html.erb
<h1>Soft Delete Lists</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Deleted at</th>
      <th>Deleted</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @soft_delete_lists.each do |list| %>
      <tr>
        <td><%= list.name %></td>
        <td><%= list.deleted_at %></td>
        <td><%= list.deleted %></td>
        <td><%= link_to 'Show', list %></td>
        <td><%= link_to 'Edit', edit_list_path(list) %></td>
        <td><%= link_to 'Delete', delete_list_path(list), method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <td><%= link_to 'Restore', restore_list_path(list), method: :patch %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>


<%= link_to 'Back to list', lists_path %>